# Generated by Django 5.0.3 on 2024-06-30 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Booking', '0002_remove_booking_date_ordered_remove_booking_duedate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='full_name',
            new_name='name',
        ),
    ]
