# Generated by Django 5.0.3 on 2024-06-30 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Booking', '0006_remove_booking_name_alter_booking_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='email',
            field=models.EmailField(editable=False, max_length=250, null=True),
        ),
    ]
