# Generated by Django 5.0.3 on 2024-06-30 22:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Booking', '0011_alter_booking_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='email',
        ),
    ]
